spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/microsoft/piggymetrics-config.git
          username: your-github-user-name
          password: your-github-personal-token-with-access-to-private-repos